export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const SET_CURRENT_ACTIVITY = "SET_CURRENT_ACTIVITY";
export const CLEAR_ACTIVITY = "CLEAR_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const ACTIVITY_ERROR = "ACTIVITY_ERROR";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";

export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const CLEAR_COMPANY = "CLEAR_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const COMPANY_ERROR = "COMPANY_ERROR";
export const FILTER_COMPANY = "FILTER_COMPANY";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUESTS = "GET_REQUESTS";
export const ADD_REQUEST = "ADD_REQUEST";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const SET_CURRENT_REQUEST = "SET_CURRENT_REQUEST";
export const CLEAR_REQUEST = "CLEAR_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const FILTER_REQUEST = "FILTER_REQUEST";
