export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const SET_CURRENT_ACTIVITY = "SET_CURRENT_ACTIVITY";
export const CLEAR_ACTIVITY = "CLEAR_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const ACTIVITY_ERROR = "ACTIVITY_ERROR";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";
export const POPULATE_SUBACTIVITIES = "POPULATE_SUBACTIVITIES";

export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const CLEAR_COMPANY = "CLEAR_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const COMPANY_ERROR = "COMPANY_ERROR";
export const FILTER_COMPANY = "FILTER_COMPANY";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUESTS = "GET_REQUESTS";
export const ADD_REQUEST = "ADD_REQUEST";
export const GET_EMAILS = "GET_EMAILS";
export const ADD_EMAIL = "ADD_EMAIL";
export const DELETE_EMAIL = "DELETE_EMAIL";
export const GET_OPEN_STATUS = "GET_OPEN_STATUS";
export const GET_OPEN_STATUS_COUNT = "GET_OPEN_STATUS_COUNT";
export const GET_30_DAYS_REQUESTS = "GET_30_DAYS_REQUESTS";
export const GET_30_DAYS_REQUESTS_COUNT = "GET_30_DAYS_REQUESTS_COUNT";

export const GET_COMPANY_REQUESTS = "GET_COMPANY_REQUESTS";
export const GET_COMPANY_OPEN_STATUS = "GET_COMPANY_OPEN_STATUS";
export const GET_COMPANY_OPEN_STATUS_COUNT = "GET_COMPANY_OPEN_STATUS_COUNT";
export const GET_COMPANY_30_DAYS_REQUESTS = "GET_COMPANY_30_DAYS_REQUESTS";
export const GET_COMPANY_30_DAYS_REQUESTS_COUNT =
  "GET_COMPANY_30_DAYS_REQUESTS_COUNT";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const SET_CURRENT_REQUEST = "SET_CURRENT_REQUEST";
export const CLEAR_REQUEST = "CLEAR_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const FILTER_REQUEST = "FILTER_REQUEST";

export const GET_MEMBER = "GET_MEMBER";
export const GET_MEMEBERS = "GET_MEMEBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const SET_CURRENT_MEMBER = "SET_CURRENT_MEMBER";
export const CLEAR_MEMBER = "CLEAR_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const MEMBER_ERROR = "MEMBER_ERROR";
export const FILTER_MEMBER = "FILTER_MEMBER";
